name = "InterpolatedRejectionSampling"
uuid = "9608d442-472c-11e9-3e14-5b72dbacd115"
desc = "Fast (multivariate) rejection sampling of discrete PDFs using Interpolation.jl"
authors = ["m-wells"]
version = "0.1.0"

[deps]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[targets]
test = ["Test","Statistics"]
